project:
  type: website
  output-dir: docs

website:
  favicon: https://raw.githubusercontent.com/pat-alt/pat-alt.github.io/main/www/favicon.ico
  title: Julia-themed Quarto
  repo-url: https://github.com/pat-alt/quarto-julia-website
  navbar:
    background: primary
    tools:
      - icon: github
        menu:
          - text: Share your thoughts
            url: https://github.com/pat-alt/quarto-julia-website/discussions/
          - text: Source Code
            url:  https://github.com/pat-alt/quarto-julia-website
  sidebar:
    logo: www/julia_quarto.gif
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Available Formats"
        contents:
          - href: examples/basic_formats/article/index.qmd
            text: "HTML Article"
          - href: examples/basic_formats/revealjs/index.qmd
            text: "Revealjs Presentation"
          - section: "PDF"
            contents:
              - href: examples/juliacon/index.qmd
              - section: "Example Articles"
                contents:
                  - href: examples/juliacon/counterfactual-explanations/index.qmd
      - section: "Package Documentation" 
        contents: 
          - href: examples/documenter/index.qmd
      - section: "Examples"
        contents: 
          - href: examples/index.qmd
            text: "List of Examples"
          - href: examples/contribute.qmd
            text: "Contribute your Work"


format:
  julia-html:
    toc: true



